(()=>{
  const qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const time12=t=>{if(!t)return'—';const [h,m]=String(t).slice(0,5).split(':').map(Number);const d=new Date();d.setHours(h,m||0,0,0);return d.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});};
  function ensureModal(){if(qs('#invoiceModal'))return;const d=document.createElement('dialog');d.id='invoiceModal';d.className='modal wide';d.innerHTML=`<div><header><div><p class="eyebrow">EM TINTING</p><h3>Invoice</h3></div><button type="button" class="x" id="invoiceClose">×</button></header><div id="invoicePreview" style="background:#fff;color:#111;padding:28px;border-radius:12px;margin:12px 0"></div><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn primary" id="invoiceEmail">Email Invoice</button><button class="btn ghost" id="invoicePrint">Print / Save PDF</button></div></div>`;document.body.appendChild(d);qs('#invoiceClose').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d)d.close()});}
  let active=null;
  function invoiceNumber(b){return `EM-${String(b.id||'').replace(/-/g,'').slice(0,8).toUpperCase()||Date.now().toString().slice(-8)}`}
  function openInvoice(id){ensureModal();const b=(state.bookings||[]).find(x=>x.id===id);if(!b)return toast('Appointment not found');const c=customerById(b.customer_id);if(!c)return toast('Customer not found');const services=(state.bookingServices||[]).filter(x=>x.booking_id===id);const total=Number(b.total_amount||b.quoted_price||services.reduce((n,x)=>n+Number(x.quantity||1)*Number(x.unit_price||0),0)||0);active={b,c,total,services};const vehicle=[b.vehicle_year,b.vehicle_make,b.vehicle_model].filter(Boolean).join(' ')||'Vehicle';const lines=services.length?services.map(x=>`<tr><td style="padding:10px 0;border-bottom:1px solid #ddd">${esc(x.description||b.service||'Service')}</td><td style="padding:10px 0;border-bottom:1px solid #ddd;text-align:right">${money(Number(x.quantity||1)*Number(x.unit_price||0))}</td></tr>`).join(''):`<tr><td style="padding:10px 0;border-bottom:1px solid #ddd">${esc(b.service||'Service')}</td><td style="padding:10px 0;border-bottom:1px solid #ddd;text-align:right">${money(total)}</td></tr>`;qs('#invoicePreview').innerHTML=`<div style="display:flex;justify-content:space-between;gap:24px"><div><div style="font-size:28px;font-weight:900">EM TINTING</div><div>Window Tint & PPF</div><div>346.804.9135</div><div>Emtinting@yahoo.com</div></div><div style="text-align:right"><div style="font-size:24px;font-weight:800">INVOICE</div><div>${invoiceNumber(b)}</div><div>${dateFmt(new Date().toISOString().slice(0,10))}</div></div></div><hr style="margin:24px 0"><div><strong>Bill To:</strong><br>${esc(customerName(c))}<br>${esc(c.email||'')}<br>${esc(c.phone||'')}</div><div style="margin-top:18px"><strong>Vehicle:</strong> ${esc(vehicle)}<br><strong>Appointment:</strong> ${esc(dateFmt(b.appointment_date))} at ${esc(time12(b.appointment_time))}</div><table style="width:100%;border-collapse:collapse;margin-top:22px"><tbody>${lines}</tbody><tfoot><tr><td style="padding-top:18px;font-weight:800">Total</td><td style="padding-top:18px;text-align:right;font-size:22px;font-weight:900">${money(total)}</td></tr></tfoot></table><p style="margin-top:28px">Thank you for choosing EM Tinting.</p>`;qs('#invoiceModal').showModal();}
  function emailInvoice(){if(!active)return;const {b,c,total,services}=active;if(!c.email)return toast('Customer email address is missing');const vehicle=[b.vehicle_year,b.vehicle_make,b.vehicle_model].filter(Boolean).join(' ')||'your vehicle';const detail=services.length?services.map(x=>`${x.description||b.service}: ${money(Number(x.quantity||1)*Number(x.unit_price||0))}`).join('\n'):`${b.service||'Service'}: ${money(total)}`;const subject=`EM Tinting Invoice ${invoiceNumber(b)}`;const body=`Hi ${c.first_name||customerName(c)},\n\nThank you for choosing EM Tinting. Here is your invoice for ${vehicle}.\n\n${detail}\n\nTotal: ${money(total)}\n\nAppointment: ${dateFmt(b.appointment_date)} at ${time12(b.appointment_time)}\n\nThank you,\nEM Tinting\n346.804.9135`;location.href=`mailto:${encodeURIComponent(c.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;}
  function printInvoice(){if(!active)return;const html=qs('#invoicePreview').innerHTML;const w=window.open('','_blank','width=850,height=900');w.document.write(`<!doctype html><html><head><title>EM Tinting Invoice</title></head><body style="font-family:Arial,sans-serif;padding:36px">${html}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close();}
  function addButton(){const card=qs('#crmAppointmentDetail .crm-action-card');if(!card||card.querySelector('[data-invoice-button]'))return;const check=qsa('button',card).find(b=>(b.getAttribute('onclick')||'').includes("checkIn('"));const m=(check?.getAttribute('onclick')||'').match(/checkIn\('([^']+)'\)/);if(!m)return;const btn=document.createElement('button');btn.type='button';btn.dataset.invoiceButton='1';btn.textContent='Send Invoice';btn.style.borderColor='#ef1b20';btn.onclick=()=>openInvoice(m[1]);const cancel=qsa('button',card).find(b=>b.textContent.includes('Cancel Appointment'));card.insertBefore(btn,cancel||null);}
  ensureModal();qs('#invoiceEmail').onclick=emailInvoice;qs('#invoicePrint').onclick=printInvoice;const obs=new MutationObserver(addButton);obs.observe(document.documentElement,{subtree:true,childList:true});setInterval(addButton,700);window.openInvoice=openInvoice;
})();