window.addEventListener('load',()=>{
  const root=document.querySelector('.main');
  const nav=document.querySelector('#nav');
  if(!root||!nav) return;

  // Sidebar groups to match the new CRM mockup.
  const buttons=[...nav.querySelectorAll('.nav-item')];
  const label=(text,before)=>{const el=document.createElement('div');el.className='crm-nav-group';el.textContent=text;nav.insertBefore(el,before||null);};
  if(!nav.querySelector('.crm-nav-group')){
    label('MAIN',buttons[0]);
    const customerBtn=buttons.find(b=>b.dataset.view==='customers');
    if(customerBtn){
      const follow=document.createElement('button');follow.className='nav-item';follow.type='button';follow.innerHTML='Follow-up Center <span class="crm-nav-badge">•</span>';follow.onclick=()=>{document.querySelector('[data-view="dashboard"]')?.click();setTimeout(()=>document.querySelector('#growthPanel')?.scrollIntoView({behavior:'smooth'}),100)};
      const reminder=document.createElement('button');reminder.className='nav-item';reminder.type='button';reminder.textContent='Reminders';reminder.onclick=()=>document.querySelector('[data-view="bookings"]')?.click();
      const reviews=document.createElement('button');reviews.className='nav-item';reviews.type='button';reviews.textContent='Review Requests';reviews.onclick=()=>{document.querySelector('[data-view="dashboard"]')?.click();setTimeout(()=>document.querySelector('#growthPanel')?.scrollIntoView({behavior:'smooth'}),100)};
      label('COMMUNICATION',customerBtn.nextSibling);nav.insertBefore(follow,customerBtn.nextSibling);nav.insertBefore(reminder,follow.nextSibling);nav.insertBefore(reviews,reminder.nextSibling);
    }
    const payBtn=buttons.find(b=>b.dataset.view==='payments');if(payBtn){label('FINANCIAL',payBtn);}
  }

  // Global search.
  const top=document.querySelector('.topbar>div');
  if(top&&!document.querySelector('.crm-global-search')){
    const search=document.createElement('input');search.className='crm-global-search';search.placeholder='Search customers, appointments, quotes...';
    search.addEventListener('input',e=>{const q=e.target.value.trim();if(q.length<2)return;const appt=document.querySelector('[data-view="bookings"]');appt?.click();const bs=document.querySelector('#bookingSearch');if(bs){bs.value=q;bs.dispatchEvent(new Event('input'));}});
    top.prepend(search);
  }

  // Appointment detail workspace.
  const workspace=document.createElement('section');workspace.id='crmAppointmentDetail';workspace.className='crm-appointment-detail';root.appendChild(workspace);
  const normalViews=[...document.querySelectorAll('.view')];
  const hideViews=()=>normalViews.forEach(v=>v.style.display='none');
  const restoreViews=()=>{normalViews.forEach(v=>v.style.display='');workspace.classList.remove('active');const active=document.querySelector('.view.active');if(active)active.style.display='block';};
  window.crmBackToAppointments=()=>{restoreViews();document.querySelector('[data-view="bookings"]')?.click();};

  const fmtTime=t=>{if(!t)return'—';const [h,m]=String(t).slice(0,5).split(':').map(Number);const d=new Date();d.setHours(h,m||0,0,0);return d.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});};
  const phone=p=>String(p||'').replace(/[^0-9+]/g,'');
  const first=c=>String(c?.first_name||'Customer').split(' ')[0];
  const esc2=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
  const warrantyCard=(w,c,b)=>`<div class="crm-ewarranty-card" id="warrantyCard"><div class="crm-card-head"><div><div class="crm-hitek">HITEK</div><small>AUTOMOTIVE WINDOW FILM</small></div><div class="crm-lifetime">LIFETIME LIMITED<br>WARRANTY</div></div><div class="crm-card-body"><dl class="crm-card-fields"><dt>CUSTOMER</dt><dd>${esc2(customerName(c))}</dd><dt>ADDRESS</dt><dd>${esc2([w.customer_address,[w.customer_city,w.customer_state,w.customer_zip].filter(Boolean).join(' ')].filter(Boolean).join(', ')||'—')}</dd><dt>VEHICLE</dt><dd>${esc2([w.vehicle_year,w.vehicle_make,w.vehicle_model].filter(Boolean).join(' ')||'—')}</dd><dt>VIN #</dt><dd>${esc2(w.vin||'—')}</dd><dt>FILM TYPE</dt><dd>${esc2(w.film_package||'—')}</dd><dt>SHADE</dt><dd>${esc2(w.shade||'—')}</dd><dt>INSTALL DATE</dt><dd>${dateFmt(w.installation_date)}</dd><dt>DEALER</dt><dd>${esc2(w.dealer_name||'EM Tinting')}</dd></dl><div class="crm-card-copy"><strong>HITEK WARRANTY</strong><p>Professionally installed HITEK automotive window film is covered against qualifying manufacturer defects under HITEK's published limited lifetime warranty terms.</p><p>Warranty eligibility remains subject to HITEK terms and applicable laws. Register the installation with HITEK using the official E‑Warranty portal.</p><div class="crm-hitek" style="font-size:25px;margin-top:22px">HITEK</div><div style="color:#ef1b20;font-weight:800">AUTHORIZED DEALER RECORD</div></div></div><div class="crm-card-footer">COAST TO COAST WARRANTY &nbsp; | &nbsp; HITEKFILMS.COM</div></div>`;

  async function loadWarranties(customerId){const {data,error}=await db.from('warranties').select('*').eq('customer_id',customerId).order('installation_date',{ascending:false});if(error){toast(error.message);return[]}return data||[];}
  async function saveWarranty(booking,c){
    const form=document.querySelector('#crmWarrantyForm');if(!form)return;
    const fd=new FormData(form);
    const payload={customer_id:booking.customer_id,booking_id:booking.id,vehicle_year:booking.vehicle_year,vehicle_make:booking.vehicle_make,vehicle_model:booking.vehicle_model,vin:booking.vin,film_brand:'HITEK',film_package:fd.get('film_package'),shade:fd.get('shade'),coverage:fd.get('coverage'),installation_date:fd.get('installation_date'),customer_address:fd.get('customer_address')||null,customer_city:fd.get('customer_city')||null,customer_state:fd.get('customer_state')||null,customer_zip:fd.get('customer_zip')||null,film_roll_number:fd.get('film_roll_number')||null,dealer_name:'EM Tinting',dealer_email:'emtinting@yahoo.com',dealer_phone:'346-804-9135',warranty_type:'HITEK lifetime limited'};
    const {error}=await db.from('warranties').insert(payload);if(error)return toast(error.message);toast('HITEK warranty record created');openAppointmentDetail(booking.id,'ewarranty');
  }
  async function deleteWarranty(id,bookingId){if(!confirm('Delete this warranty record?'))return;const {error}=await db.from('warranties').delete().eq('id',id);if(error)return toast(error.message);toast('Warranty deleted');openAppointmentDetail(bookingId,'ewarranty');}
  function printWarranty(){const card=document.querySelector('#warrantyCard');if(!card)return;const win=window.open('','_blank','width=900,height=700');win.document.write(`<html><head><title>EM Tinting HITEK Warranty</title><style>body{font-family:Arial;background:#08090b;color:white;padding:30px}*{box-sizing:border-box}${document.querySelector('link[href="crm-modern.css"]')?'':''}</style></head><body>${card.outerHTML}</body></html>`);win.document.close();setTimeout(()=>win.print(),400);}

  async function renderWarrantyPanel(booking,c){
    const warranties=await loadWarranties(booking.customer_id);const active=warranties[0]||null;
    const films=['Standard','Hybrid','PPF Pro','PPF Ultra','Ceramic IR','Ceramic Plus','Carbon IR','Ceramic Black','Ceramic Ultra','Classic'];
    const left=`<div class="crm-ewarranty-left"><h3>HITEK E‑WARRANTY</h3><div class="crm-green">Lifetime Warranty</div><p class="muted">Create and manage HITEK warranty records for your customers.</p><button class="btn primary crm-warranty-create" id="showWarrantyForm">+ Create HITEK Warranty</button><div class="crm-existing"><strong>EXISTING WARRANTIES</strong>${warranties.length?warranties.map((w,i)=>`<div class="crm-warranty-item" data-warranty-index="${i}"><strong>W-${String(w.id).slice(0,4).toUpperCase()}</strong> <span class="crm-green">Active</span><small>${[w.vehicle_year,w.vehicle_make,w.vehicle_model].filter(Boolean).join(' ')}</small><small>${esc2(w.film_package||'')} ${esc2(w.shade||'')}</small><small>Installed: ${dateFmt(w.installation_date)}</small></div>`).join(''):'<div class="empty">No warranties yet</div>'}</div></div>`;
    const center=active?warrantyCard(active,c,booking):`<div class="crm-ewarranty-card" style="display:grid;place-items:center;min-height:420px"><div style="text-align:center;position:relative"><div class="crm-hitek">HITEK</div><h3>No warranty created yet</h3><p class="muted">Create a warranty record to preview the card here.</p></div></div>`;
    const actions=`<div class="crm-ewarranty-actions"><button onclick="window.crmPrintWarranty()">View / Print</button><a href="https://hitekfilms.com/e-warranty/" target="_blank" rel="noopener">Register with HITEK ↗</a><a href="mailto:${esc2(c.email||'')}?subject=${encodeURIComponent('Your EM Tinting HITEK warranty record')}">Email Customer</a><a href="sms:${phone(c.phone)}?body=${encodeURIComponent(`Hi ${first(c)}, your EM Tinting HITEK warranty record is ready. Thank you for choosing EM Tinting!`)}">Text Customer</a>${active?`<button class="delete" onclick="window.crmDeleteWarranty('${active.id}','${booking.id}')">Delete Warranty</button>`:''}</div>`;
    const form=`<div id="warrantyFormWrap" class="form-section" style="display:none;margin-top:16px"><h4>HITEK WARRANTY REGISTRATION DETAILS</h4><form id="crmWarrantyForm" class="crm-warranty-form"><label>Film Type / Series<select name="film_package" required>${films.map(f=>`<option>${f}</option>`).join('')}</select></label><label>Shade (%)<input name="shade" placeholder="20%" required></label><label>Coverage<input name="coverage" placeholder="Full vehicle + windshield"></label><label>Installation Date<input name="installation_date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Film Roll #<input name="film_roll_number" placeholder="Optional"></label><label>Address<input name="customer_address" placeholder="Customer address"></label><label>City<input name="customer_city"></label><label>State<input name="customer_state" value="TX"></label><label>ZIP Code<input name="customer_zip"></label><div class="span2" style="display:flex;gap:10px"><button class="btn primary" type="submit">Save Warranty Record</button><a class="btn ghost" href="https://hitekfilms.com/e-warranty/" target="_blank" rel="noopener">Open Official HITEK E‑Warranty</a></div></form></div>`;
    return `<div class="crm-ewarranty-layout">${left}${center}${actions}</div><div class="crm-note">ⓘ HITEK warranty coverage is subject to HITEK's official terms and applicable law. Use “Register with HITEK” to submit the installation through HITEK's official E‑Warranty portal.</div>${form}`;
  }

  async function openAppointmentDetail(id,tab='details'){
    const b=(state.bookings||[]).find(x=>x.id===id);if(!b)return toast('Appointment not found');const c=customerById(b.customer_id);if(!c)return toast('Customer not found');
    hideViews();workspace.classList.add('active');document.querySelector('#pageTitle').textContent='Appointment';
    const vehicle=[b.vehicle_year,b.vehicle_make,b.vehicle_model].filter(Boolean).join(' ')||'Vehicle not entered';
    workspace.innerHTML=`<button class="crm-back-btn" onclick="crmBackToAppointments()">← Back to appointments</button><div class="crm-breadcrumb">Appointments &nbsp;›&nbsp; Appointment #${String(b.id).slice(0,8).toUpperCase()}</div><div class="crm-detail-grid"><div class="crm-appt-card"><div class="crm-appt-title"><h2>Appointment #${String(b.id).slice(0,8).toUpperCase()}</h2><span class="crm-confirmed">${b.appointment_confirmed?'Confirmed':esc2(b.status||'Booked')}</span></div><div class="crm-appt-meta"><div><small>Date</small>${dateFmt(b.appointment_date)}</div><div><small>Time</small>${fmtTime(b.appointment_time)}</div><div><small>Customer</small>${esc2(customerName(c))}</div><div><small>Phone</small>${esc2(c.phone||'—')}</div><div><small>Vehicle</small>${esc2(vehicle)}</div><div><small>Status</small>${esc2(b.status||'booked')}</div></div></div><div class="crm-action-card"><button onclick="window.openAppointmentText('${b.id}','confirmation')">Text Confirmation</button><button onclick="window.openAppointmentText('${b.id}','reminder')">24h Reminder</button><button onclick="window.openAppointmentText('${b.id}','reschedule')">Text Reschedule</button><button onclick="window.openAppointmentText('${b.id}','cancellation')">Text Cancellation</button><button onclick="checkIn('${b.id}')">Check-in</button><button onclick="checkOut('${b.id}')">Check-out</button><button class="danger" onclick="cancelAppointment('${b.id}')">Cancel Appointment</button></div></div><div class="crm-tabs"><button class="crm-tab" data-tab="details">Details</button><button class="crm-tab" data-tab="services">Services</button><button class="crm-tab" data-tab="payments">Payments</button><button class="crm-tab" data-tab="ewarranty">E‑Warranty (HITEK)</button><button class="crm-tab" data-tab="notes">Notes</button><button class="crm-tab" data-tab="activity">Activity</button></div><div id="crmPanelDetails" class="crm-tab-panel"><div class="crm-section-placeholder"><strong>${esc2(b.service||'Appointment')}</strong><br>${esc2(vehicle)}<br>${esc2(b.notes||'No appointment notes')}</div></div><div id="crmPanelServices" class="crm-tab-panel"><div class="crm-section-placeholder">Service total: ${money(b.total_amount||b.quoted_price||0)}<br>Film package: ${esc2(b.tint_package||'Not selected')}</div></div><div id="crmPanelPayments" class="crm-tab-panel"><div class="crm-section-placeholder">Deposit recorded: ${money(b.deposit_amount||0)}<br>Use the Payments page for full payment history.</div></div><div id="crmPanelEwarranty" class="crm-tab-panel"></div><div id="crmPanelNotes" class="crm-tab-panel"><div class="crm-section-placeholder">${esc2(b.notes||'No notes yet')}</div></div><div id="crmPanelActivity" class="crm-tab-panel"><div class="crm-section-placeholder">Created ${b.created_at?new Date(b.created_at).toLocaleString():'—'}<br>Status: ${esc2(b.status||'booked')}</div></div>`;
    const activate=async name=>{workspace.querySelectorAll('.crm-tab,.crm-tab-panel').forEach(x=>x.classList.remove('active'));workspace.querySelector(`[data-tab="${name}"]`)?.classList.add('active');const panel=workspace.querySelector(`#crmPanel${name.charAt(0).toUpperCase()+name.slice(1)}`);if(panel){panel.classList.add('active');if(name==='ewarranty'){panel.innerHTML='<div class="empty">Loading warranty...</div>';panel.innerHTML=await renderWarrantyPanel(b,c);panel.querySelector('#showWarrantyForm')?.addEventListener('click',()=>{const f=panel.querySelector('#warrantyFormWrap');f.style.display=f.style.display==='none'?'block':'none';});panel.querySelector('#crmWarrantyForm')?.addEventListener('submit',e=>{e.preventDefault();saveWarranty(b,c);});}}};
    workspace.querySelectorAll('.crm-tab').forEach(btn=>btn.onclick=()=>activate(btn.dataset.tab));await activate(tab);
  }
  window.openAppointmentDetail=openAppointmentDetail;window.crmPrintWarranty=printWarranty;window.crmDeleteWarranty=deleteWarranty;

  // Add a clear View button to appointment rows after every render.
  const enhance=()=>document.querySelectorAll('#bookingsTable tbody tr').forEach(row=>{const actions=row.querySelector('.table-actions');if(!actions||actions.querySelector('.crm-view-btn'))return;const check=[...actions.querySelectorAll('button')].find(x=>(x.getAttribute('onclick')||'').includes("checkIn('"));if(!check)return;const m=(check.getAttribute('onclick')||'').match(/checkIn\('([^']+)'\)/);if(!m)return;const btn=document.createElement('button');btn.type='button';btn.className='crm-view-btn';btn.textContent='View Details';btn.onclick=()=>openAppointmentDetail(m[1]);actions.prepend(btn);});
  const obs=new MutationObserver(()=>setTimeout(enhance,0));const bt=document.querySelector('#bookingsTable');if(bt)obs.observe(bt,{childList:true,subtree:true});setTimeout(enhance,500);
});