const SUPABASE_URL='https://neuginokjfvnkmlzhwoa.supabase.co';
const SUPABASE_KEY='sb_publishable_T-XFCPWnkn_meQPK0AKA6A_hRvfRXGk';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const OWNER_EMAIL='emtinting@yahoo.com';
const state={customers:[],bookings:[],bookingServices:[],catalog:[],quotes:[],jobs:[],payments:[]};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
const dateFmt=v=>v?new Date(`${v}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'—';
const customerName=c=>c?`${c.first_name||''} ${c.last_name||''}`.trim():'Unknown';
const customerById=id=>state.customers.find(c=>c.id===id);
const phoneHref=(prefix,p)=>prefix+String(p||'').replace(/[^0-9+]/g,'');
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function pill(v){return `<span class="pill ${esc(v)}">${esc(String(v||'').replaceAll('_',' '))}</span>`}
function showAuth(){$('#authScreen').classList.remove('hidden');$('#app').classList.add('hidden')}
function showApp(){$('#authScreen').classList.add('hidden');$('#app').classList.remove('hidden')}

async function boot(){const {data:{session}}=await db.auth.getSession();if(session?.user?.email?.toLowerCase()===OWNER_EMAIL){showApp();await loadAll()}else showAuth()}
db.auth.onAuthStateChange(async(event,session)=>{if(event==='PASSWORD_RECOVERY'){showAuth();$('#loginForm').classList.add('hidden');$('#signupForm').classList.add('hidden');$('#recoveryForm').classList.remove('hidden');$('#authMessage').textContent='Enter a new password for your CRM.'}if(event==='SIGNED_IN'&&session?.user?.email?.toLowerCase()===OWNER_EMAIL){showApp();await loadAll()}});
$('#showSignup').addEventListener('click',()=>$('#signupForm').classList.toggle('hidden'));
$('#forgotPassword').addEventListener('click',async()=>{const redirectTo=location.href.split('#')[0].split('?')[0];$('#authMessage').textContent='Sending password reset...';const {error}=await db.auth.resetPasswordForEmail(OWNER_EMAIL,{redirectTo});$('#authMessage').textContent=error?error.message:'Password reset email sent.'});
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('#loginEmail').value.trim().toLowerCase();if(email!==OWNER_EMAIL)return $('#authMessage').textContent='This CRM is restricted to the EM Tinting owner account.';const {error}=await db.auth.signInWithPassword({email,password:$('#loginPassword').value});if(error)$('#authMessage').textContent=error.message});
$('#signupForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('#signupEmail').value.trim().toLowerCase();if(email!==OWNER_EMAIL)return $('#authMessage').textContent='Use the EM Tinting owner email.';const {data,error}=await db.auth.signUp({email,password:$('#signupPassword').value,options:{emailRedirectTo:location.href.split('#')[0].split('?')[0]}});$('#authMessage').textContent=error?error.message:(data.session?'Account created. Loading CRM...':'Account created. Check your email to confirm the login.')});
$('#recoveryForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await db.auth.updateUser({password:$('#recoveryPassword').value});if(error)return $('#authMessage').textContent=error.message;$('#recoveryForm').classList.add('hidden');showApp();await loadAll()});
$('#signOut').addEventListener('click',async()=>{await db.auth.signOut();location.reload()});$('#refreshBtn').addEventListener('click',loadAll);

$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(`#${b.dataset.view}View`).classList.add('active');$('#pageTitle').textContent=b.textContent});
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.open==='appointmentModal')prepareAppointment();$(`#${b.dataset.open}`).showModal()}));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{$(`#${b.dataset.close}`).close()}));

async function loadAll(){
  $('#refreshBtn').textContent='Loading...';
  const [customers,bookings,bookingServices,catalog,quotes,jobs,payments]=await Promise.all([
    db.from('customers').select('*').order('created_at',{ascending:false}),db.from('bookings').select('*').order('appointment_date',{ascending:true}),db.from('booking_services').select('*').order('sort_order'),db.from('service_catalog').select('*').eq('active',true).order('sort_order'),db.from('quotes').select('*').order('created_at',{ascending:false}),db.from('jobs').select('*').order('scheduled_date',{ascending:true}),db.from('payments').select('*').order('created_at',{ascending:false})]);
  const responses=[customers,bookings,bookingServices,catalog,quotes,jobs,payments];const err=responses.find(x=>x.error)?.error;if(err){toast(err.message);$('#refreshBtn').textContent='Refresh';return}
  state.customers=customers.data||[];state.bookings=bookings.data||[];state.bookingServices=bookingServices.data||[];state.catalog=catalog.data||[];state.quotes=quotes.data||[];state.jobs=jobs.data||[];state.payments=payments.data||[];renderAll();$('#refreshBtn').textContent='Refresh';
}
function renderAll(){renderDashboard();renderBookings();renderCustomers();renderQuotes();renderJobs();renderPayments();fillCustomerSelects();fillCatalog()}
function renderDashboard(){const today=new Date().toISOString().slice(0,10);const upcoming=state.bookings.filter(b=>b.appointment_date>=today&&!['cancelled','completed'].includes(b.status));const openQuotes=state.quotes.filter(q=>['draft','sent'].includes(q.status));const openJobs=state.jobs.filter(j=>!['completed','cancelled','no_show'].includes(j.status));const revenue=state.payments.filter(p=>p.status==='paid').reduce((n,p)=>n+(p.payment_type==='refund'?-Number(p.amount):Number(p.amount)),0);$('#statUpcoming').textContent=upcoming.length;$('#statQuotes').textContent=openQuotes.length;$('#statJobs').textContent=openJobs.length;$('#statRevenue').textContent=money(revenue);$('#nextBookings').innerHTML=upcoming.slice(0,6).map(b=>{const c=customerById(b.customer_id);return `<div class="list-item"><div><strong>${esc(customerName(c))}</strong><small>${esc(b.service)} · ${dateFmt(b.appointment_date)} ${(b.appointment_time||'').slice(0,5)}</small></div>${pill(b.appointment_confirmed?'confirmed':b.status)}</div>`}).join('')||'<div class="empty">No upcoming appointments</div>';$('#recentCustomers').innerHTML=state.customers.slice(0,6).map(c=>`<div class="list-item"><div><strong>${esc(customerName(c))}</strong><small>${esc(c.phone)}${c.company?' · '+esc(c.company):''}</small></div></div>`).join('')||'<div class="empty">No customers yet</div>'}
function renderBookings(filter=''){let rows=state.bookings;if(filter){const q=filter.toLowerCase();rows=rows.filter(b=>{const c=customerById(b.customer_id);return [customerName(c),c?.phone,b.service,b.vehicle_year,b.vehicle_make,b.vehicle_model,b.vin].join(' ').toLowerCase().includes(q)})}$('#bookingsTable').innerHTML=table(['Customer','Schedule','Vehicle','Service / Total','Status','Actions'],rows.map(b=>{const c=customerById(b.customer_id);const vehicle=[b.vehicle_year,b.vehicle_make,b.vehicle_model,b.vehicle_color].filter(Boolean).join(' ');const total=Number(b.total_amount||b.quoted_price||0);const confirm=b.appointment_confirmed?'confirmed':b.status;return [customerName(c),`${dateFmt(b.appointment_date)} ${(b.appointment_time||'').slice(0,5)}`,vehicle||'—',`${esc(b.service)}<br><strong>${money(total)}</strong>`,pill(confirm),`<div class="table-actions"><a href="${phoneHref('tel:',c?.phone)}">Call</a><a href="${phoneHref('sms:',c?.phone)}">Text</a><button onclick="logConfirmationCall('${b.id}')">Log call (${b.confirmation_calls||0})</button><button onclick="toggleConfirmed('${b.id}',${!b.appointment_confirmed})">${b.appointment_confirmed?'Unconfirm':'Confirm'}</button><button onclick="checkIn('${b.id}')">Check-in</button><button onclick="checkOut('${b.id}')">Check-out</button><button onclick="bookingToJob('${b.id}')">Make job</button></div>`]}))}
function renderCustomers(filter=''){let rows=state.customers;if(filter){const q=filter.toLowerCase();rows=rows.filter(c=>[c.first_name,c.last_name,c.phone,c.email,c.company].join(' ').toLowerCase().includes(q))}$('#customersTable').innerHTML=table(['Customer','Phone','Email','Company','Actions'],rows.map(c=>[customerName(c),c.phone,c.email||'—',c.company||'—',`<div class="table-actions"><a href="${phoneHref('tel:',c.phone)}">Call</a><a href="${phoneHref('sms:',c.phone)}">Text</a></div>`]))}
function renderQuotes(){$('#quotesTable').innerHTML=table(['Customer','Service','Film','Amount','Status','Actions'],state.quotes.map(q=>{const c=customerById(q.customer_id);return [customerName(c),q.service,q.film_package||'—',money(q.amount),pill(q.status),`<div class="table-actions"><button onclick="updateQuoteStatus('${q.id}','sent')">Sent</button><button onclick="quoteToJob('${q.id}')">Make job</button><button onclick="updateQuoteStatus('${q.id}','declined')">Decline</button></div>`]}))}
function renderJobs(){$('#jobsTable').innerHTML=table(['Customer','Service','Schedule','Total','Status','Actions'],state.jobs.map(j=>{const c=customerById(j.customer_id);return [customerName(c),j.service,`${dateFmt(j.scheduled_date)} ${(j.scheduled_time||'').slice(0,5)}`,money(j.total_amount),pill(j.status),`<div class="table-actions"><button onclick="updateJobStatus('${j.id}','in_progress')">Start</button><button onclick="updateJobStatus('${j.id}','completed')">Complete</button></div>`]}))}
function renderPayments(){$('#paymentsTable').innerHTML=table(['Customer','Amount','Type','Method','Status','Date'],state.payments.map(p=>{const c=customerById(p.customer_id);return [customerName(c),money(p.amount),pill(p.payment_type),(p.method||'—').replaceAll('_',' '),pill(p.status),new Date(p.paid_at||p.created_at).toLocaleDateString()]}))}
function table(headers,rows){if(!rows.length)return'<div class="empty">Nothing here yet</div>';return `<table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${typeof c==='string'&&c.startsWith('<')?c:typeof c==='string'&&c.includes('<br>')?c:esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function fillCustomerSelects(){const options='<option value="">Select customer</option>'+state.customers.map(c=>`<option value="${c.id}">${esc(customerName(c))} · ${esc(c.phone)}</option>`).join('');['quoteCustomer','jobCustomer','paymentCustomer'].forEach(id=>{$(`#${id}`).innerHTML=options});$('#apptExistingCustomer').innerHTML='<option value="">New customer</option>'+state.customers.map(c=>`<option value="${c.id}">${esc(customerName(c))} · ${esc(c.phone)}</option>`).join('')}
function fillCatalog(){$('#catalogSelect').innerHTML='<option value="">Choose service...</option>'+state.catalog.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
$('#bookingSearch').addEventListener('input',e=>renderBookings(e.target.value));$('#customerSearch').addEventListener('input',e=>renderCustomers(e.target.value));

function prepareAppointment(){$('#appointmentForm').reset();$('#apptExistingCustomer').value='';$('#apptDate').value=new Date().toISOString().slice(0,10);$('#apptTime').value='10:00';$('#serviceLines').innerHTML='<div class="empty">No services added</div>';updatePhoneLinks();calculateAppointment()}
$('#apptExistingCustomer').addEventListener('change',()=>{const c=customerById($('#apptExistingCustomer').value);if(!c){['apptFirst','apptLast','apptPhone','apptEmail','apptCompany'].forEach(id=>$('#'+id).value='');return updatePhoneLinks()}$('#apptFirst').value=c.first_name||'';$('#apptLast').value=c.last_name||'';$('#apptPhone').value=c.phone||'';$('#apptEmail').value=c.email||'';$('#apptCompany').value=c.company||'';updatePhoneLinks()});
$('#apptPhone').addEventListener('input',updatePhoneLinks);function updatePhoneLinks(){const p=$('#apptPhone').value;$('#apptCall').href=phoneHref('tel:',p);$('#apptText').href=phoneHref('sms:',p)}
$('#catalogSelect').addEventListener('change',()=>{const item=state.catalog.find(x=>x.id===$('#catalogSelect').value);if(item)addServiceRow({description:item.name,film_package:item.film_package,quantity:1,unit_price:item.default_price});$('#catalogSelect').value='' });
$('#addServiceLine').addEventListener('click',()=>addServiceRow());
function addServiceRow(v={}){const empty=$('#serviceLines .empty');if(empty)empty.remove();const row=document.createElement('div');row.className='service-row';row.innerHTML=`<label>Service<input class="svc-desc" value="${esc(v.description||'')}" placeholder="Service"></label><label>Film<select class="svc-film"><option value="">None</option><option>Carbon</option><option>Ceramic IR</option><option>Ceramic Plus</option></select></label><label>Qty<input class="svc-qty" type="number" min="0.01" step="0.01" value="${Number(v.quantity||1)}"></label><label>Price<input class="svc-price" type="number" min="0" step="0.01" value="${Number(v.unit_price||0)}"></label><button class="remove-line" type="button">Remove</button>`;row.querySelector('.svc-film').value=v.film_package||'';row.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',calculateAppointment));row.querySelector('.remove-line').addEventListener('click',()=>{row.remove();if(!$('#serviceLines').children.length)$('#serviceLines').innerHTML='<div class="empty">No services added</div>';calculateAppointment()});$('#serviceLines').appendChild(row);calculateAppointment()}
['apptDiscount','apptTaxRate','apptTaxExempt'].forEach(id=>$('#'+id).addEventListener('input',calculateAppointment));
function getServiceRows(){return [...document.querySelectorAll('#serviceLines .service-row')].map((r,i)=>({description:r.querySelector('.svc-desc').value.trim(),film_package:r.querySelector('.svc-film').value||null,quantity:Number(r.querySelector('.svc-qty').value||1),unit_price:Number(r.querySelector('.svc-price').value||0),sort_order:i})).filter(x=>x.description)}
function calculateAppointment(){const subtotal=getServiceRows().reduce((n,x)=>n+x.quantity*x.unit_price,0);const discount=Math.min(subtotal,Number($('#apptDiscount').value||0));const rate=$('#apptTaxExempt').checked?0:Number($('#apptTaxRate').value||0)/100;const total=(subtotal-discount)*(1+rate);$('#apptSubtotal').textContent=money(subtotal);$('#apptTotal').textContent=money(total);return{subtotal,discount,rate,total}}

$('#appointmentForm').addEventListener('submit',async e=>{e.preventDefault();const services=getServiceRows();const totals=calculateAppointment();let customerId=$('#apptExistingCustomer').value||null;const customerPayload={first_name:$('#apptFirst').value.trim(),last_name:$('#apptLast').value.trim(),phone:$('#apptPhone').value.trim(),email:$('#apptEmail').value.trim()||null,company:$('#apptCompany').value.trim()||null,updated_at:new Date().toISOString()};if(customerId){const {error}=await db.from('customers').update(customerPayload).eq('id',customerId);if(error)return toast(error.message)}else{const {data,error}=await db.from('customers').insert(customerPayload).select('id').single();if(error)return toast(error.message);customerId=data.id}
  const serviceSummary=$('#apptSummary').value.trim()||services.map(x=>x.description).join(', ')||'Window tint';const payload={customer_id:customerId,appointment_date:$('#apptDate').value,appointment_time:$('#apptTime').value,service:serviceSummary,vehicle_year:$('#apptYear').value.trim()||null,vehicle_make:$('#apptMake').value.trim()||null,vehicle_model:$('#apptModel').value.trim()||null,vehicle_color:$('#apptColor').value.trim()||null,vin:$('#apptVin').value.trim()||null,ro_number:$('#apptRo').value.trim()||null,lease_number:$('#apptLease').value.trim()||null,mileage:$('#apptMileage').value?Number($('#apptMileage').value):null,salesman:$('#apptSalesman').value.trim()||null,technician_1:$('#apptTech1').value.trim()||null,technician_2:$('#apptTech2').value.trim()||null,technician_3:$('#apptTech3').value.trim()||null,appointment_confirmed:$('#apptConfirmed').checked,confirmation_text_requested:$('#apptTextConfirm').checked,discount_amount:totals.discount,tax_exempt:$('#apptTaxExempt').checked,tax_rate:totals.rate,subtotal_amount:totals.subtotal,total_amount:totals.total,quoted_price:totals.total,notes:$('#apptNotes').value.trim()||null,status:'booked',source:'crm'};
  const {data:booking,error}=await db.from('bookings').insert(payload).select('id').single();if(error)return toast(error.message);if(services.length){const {error:svcError}=await db.from('booking_services').insert(services.map(x=>({...x,booking_id:booking.id})));if(svcError)return toast(svcError.message)}$('#appointmentModal').close();toast('Appointment saved');await loadAll()});

$('#customerForm').addEventListener('submit',async e=>{e.preventDefault();const payload={first_name:$('#customerFirst').value.trim(),last_name:$('#customerLast').value.trim(),phone:$('#customerPhone').value.trim(),email:$('#customerEmail').value.trim()||null,company:$('#customerCompany').value.trim()||null};const {error}=await db.from('customers').insert(payload);if(error)return toast(error.message);$('#customerModal').close();e.target.reset();toast('Customer added');await loadAll()});
$('#quoteForm').addEventListener('submit',async e=>{e.preventDefault();const film=$('#quoteFilm')?.value||document.querySelector('input[name="quoteFilm"]:checked')?.value||null;const payload={customer_id:$('#quoteCustomer').value,service:$('#quoteService').value.trim(),film_package:film,amount:Number($('#quoteAmount').value),notes:$('#quoteNotes').value.trim()||null,status:'draft'};const {error}=await db.from('quotes').insert(payload);if(error)return toast(error.message);$('#quoteModal').close();e.target.reset();toast('Quote saved');await loadAll()});
$('#jobForm').addEventListener('submit',async e=>{e.preventDefault();const payload={customer_id:$('#jobCustomer').value,service:$('#jobService').value.trim(),scheduled_date:$('#jobDate').value||null,scheduled_time:$('#jobTime').value||null,total_amount:Number($('#jobTotal').value||0),status:'scheduled'};const {error}=await db.from('jobs').insert(payload);if(error)return toast(error.message);$('#jobModal').close();e.target.reset();toast('Job saved');await loadAll()});
$('#paymentForm').addEventListener('submit',async e=>{e.preventDefault();const payload={customer_id:$('#paymentCustomer').value,amount:Number($('#paymentAmount').value),payment_type:$('#paymentType').value,method:$('#paymentMethod').value,status:'paid',paid_at:new Date().toISOString()};const {error}=await db.from('payments').insert(payload);if(error)return toast(error.message);$('#paymentModal').close();e.target.reset();toast('Payment added');await loadAll()});

window.logConfirmationCall=async id=>{const b=state.bookings.find(x=>x.id===id);const {error}=await db.from('bookings').update({confirmation_calls:Number(b?.confirmation_calls||0)+1,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);toast('Confirmation call logged');await loadAll()};
window.toggleConfirmed=async(id,value)=>{const {error}=await db.from('bookings').update({appointment_confirmed:value,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);toast(value?'Appointment confirmed':'Confirmation removed');await loadAll()};
window.checkIn=async id=>{const {error}=await db.from('bookings').update({checked_in_at:new Date().toISOString(),status:'in_progress',updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);toast('Customer checked in');await loadAll()};
window.checkOut=async id=>{const {error}=await db.from('bookings').update({checked_out_at:new Date().toISOString(),status:'completed',updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);toast('Customer checked out');await loadAll()};
window.updateQuoteStatus=async(id,status)=>{const {error}=await db.from('quotes').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);toast('Quote updated');await loadAll()};
window.updateJobStatus=async(id,status)=>{const changes={status,updated_at:new Date().toISOString()};if(status==='completed')changes.completed_at=new Date().toISOString();const {error}=await db.from('jobs').update(changes).eq('id',id);if(error)return toast(error.message);toast('Job updated');await loadAll()};
window.bookingToJob=async id=>{const b=state.bookings.find(x=>x.id===id);if(!b)return;if(state.jobs.some(j=>j.booking_id===id))return toast('This appointment already has a job');const payload={customer_id:b.customer_id,booking_id:b.id,service:b.service,scheduled_date:b.appointment_date,scheduled_time:b.appointment_time,total_amount:Number(b.total_amount||b.quoted_price||0),status:'scheduled',notes:b.notes||null};const {error}=await db.from('jobs').insert(payload);if(error)return toast(error.message);toast('Appointment converted to job');await loadAll()};
window.quoteToJob=async id=>{const q=state.quotes.find(x=>x.id===id);if(!q)return;if(state.jobs.some(j=>j.quote_id===id))return toast('This quote already has a job');const {error}=await db.from('jobs').insert({customer_id:q.customer_id,quote_id:q.id,service:q.service,total_amount:Number(q.amount||0),status:'scheduled',notes:q.notes||null});if(error)return toast(error.message);await db.from('quotes').update({status:'accepted',updated_at:new Date().toISOString()}).eq('id',id);toast('Quote accepted and job created');await loadAll()};
boot();